# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa41e454cd3078014769fd1305ab68e7dab7b387a1fa0af7349618c114c3513abc9a8ed27051a83414f05d06606a6b5793129122bc0935b8e4aca6d6f24e47a2
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: '+13479348636'

test:
  secret_key_base: d5af88d9c248aa77d89757f4ab6ad96cba83ec94257aadd14ed5aa12df6c6505076767b8dcc070f545ef4cff3805662cfda2c63947280266f97b01aa46228c43
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: '+13479348636'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: '+13479348636'


